OSTP/PhysicsArtofModelling

- tex/Introduction.tex
- tex/ModelAndExperiment.tex
- tex/PhysicsArtOfModelling.tex
Ch1
- Added a question at beginning
- Added some checkpoints
- Added "Emma's Thoughts"
- Added a quote (?)
- Added some "Research and Reflect" questions at the end
**Fix some structural issues here.
Ch2
- Started a end of chapter question & solution
> Ch1 template trial and Ch2 end Q

- tex/NewtonsLaws.tex
Summary could be better, but Emma and Olivia can take care of that :-).
Needs:
- A couple of worked out problems
- Things to try at home
- A couple of more checkpoint questions
- Some more questions on researching applications or historical context
Note that this chapter is only outlining Newton's Laws and how to set problems up. The next chapter will focus on applying them.
> Finalized draft of Newton's Law Chapter

- tex/Introduction.tex
- tex/NewtonsLaws.tex
- tex/PhysicsArtOfModelling.tex
Ch1
- Added m/c question
Ch5 reviewed typos
- 5.1.1. Newtons Laws: I think that the accelerating train description, a diagram would be helpful for visualizing the concepts.
- 5.1.3: Newtons Third Law: “However, inanimate objet(s).” - Added the s
5.2 - Force, the normal force: “from the surface to the object in such as way” - changed to “a way”
5.3 - Drag forces: “tunnel to measure the drage force” - took out the e
5.3 - Spring forces: “exerted by those materials and object(s)” - added the s
5.4.3 - Using Newton’s Second Law: - “all forces exerted on a object” - replaced a with “an”
- “The force of gravity…” - something up with xhat here, changed this.
- Footnote: “Since we have two equations…fully mode(l) the motion of the block” - I added the l
> may 29/30 edits

- tex/DescribingMotionIn1D.tex
- tex/DescribingMotionInND.tex
- tex/PhysicsArtOfModelling.tex
*New environment since last pull request: 
tQuestion: Questions for the "Thinking about the material" section. Includes a counter. Works for short answer and multiple choice. 
Changes to make when switching over: 
I still couldn’t get the itemized lists to work without brackets, so you still have to add brackets: {\item \item \item } For the learning objectives and chapter summaries. 
Opening Question: Change to \begin{opening} 
If multiple choice: \begin{opening} 
\begin{MCquestion}{Put your question here}
\item 
\item 
\item 
\end{MCquestion} 
\end{opening} 
Checkpoints: Same as \begin{opening} except that its \begin{checkpoint} 
Student opinion: change from \begin{studentopinion} to \begin{studentOpinion} 
\begin{studentOpinion}{Your Name} Your Content \end{studentOpinion}
Important …
> Updated Environments and Motion in 1D and ND chapters

- Latex conventions and formatting.tex
This document is for keeping track of all the latex/formatting conventions we use
> Added document for latex conventions

- tex/DescribingMotionInND.tex
- tex/PhysicsArtOfModelling.tex
> Minor Changes to Motion in ND

- tex/PhysicsArtOfModelling.tex
+ adding package to support columns
> Changing Key Takeaway environment

- tex/PhysicsArtOfModelling.tex
Will add a chapter that uses these environments shortly.
For multiple choice you just have to write \correct after the correct answer.
For short answer, \begin{answer} Your answer here \end{answer}
> Added ability to hide/show answers

- tex/PhysicsArtOfModelling.tex
- tex/WorkEnergy.tex
The chapter has been updated to use the new answer commands/environments.
> WorkEnergy using answer environments

- tex/PotentialECons.tex
Just have to review and complete Thinking About the Material section
> Additions to Potential E Chapter

- tex/PhysicsArtOfModelling.tex
Changed so that the chapter opening questions don't break across pages.
> Minor environment change

- tex/PhysicsArtOfModelling.tex
> Deleted old environments, switched colours, added Review environment

- tex/Introduction.tex
Still things to do for this chapter
> Edits to chapter 1

- tex/PhysicsArtOfModelling.tex
Added a link to the solution from the question. This may mess up other chapters when you try to run them - I'm going to update them asap.
How it works:
add a label to the solution: eg. \label{soln:introduction:chemtrails}. In the problem, just add a set of curly brackets before the problem that says {soln:introduction:chemtrails}.
I also changed the solution environment so that when you reference the problem you dont have to do {\ref{prob:...}}, just write {prob:...}.
Also I'm trying out a "Reflect and Research" box, really just to add a bit of colour to the "Thinking About the Material" section. May or may not keep it. The environment is called "reflectresearch".
> Environments

- tex/FluidMechanics.tex
> Thought box fluids

- tex/Gauss.tex
These changes were made to the Gauss chapter yesterday
> Small formatting changes

- tex/Potential.tex
Still formatting changes. There are also some wording changes.
> Formatting

- tex/ChargesFields.tex
In progress changes to charges and fields chapter. Figure to be added; new thought boxes in progress
> Olivia charges fields

- tex/Potential.tex
Checked problem 2 - minor edits
> Potential_Problem2Edits

- tex/Current.tex
Other thought boxes in progress, need to double check problem 2
> Currents edits + thought box

- tex/MagneticForce.tex
To do:
- trying to figure out a thought box for dipole moments
- checking end of chapter problems
> Edits + thought box
